/*
 *
 *  * Copyright (c) 2024 Cozary
 *  *
 *  * This file is part of TBOI Trinkets, a mod made for Minecraft.
 *  *
 *  * TBOI Trinkets is free software: you can redistribute it and/or modify it
 *  * under the terms of the GNU General Public License as published
 *  * by the Free Software Foundation, either version 3 of the License, or
 *  * (at your option) any later version.
 *  *
 *  * TBOI Trinkets is distributed in the hope that it will be useful, but
 *  * WITHOUT ANY WARRANTY; without even the implied warranty of
 *  * MERCHANTABILITY or FITNESS FOR PARTICULAR PURPOSE.  See the
 *  * GNU General Public License for more details.
 *  *
 *  * You should have received a copy of the GNU General Public License
 *  * License along with TBOI Trinkets.  If not, see <https://www.gnu.org/licenses/>.
 *
 */

package com.cozary.tboit.loot;

import com.cozary.tboit.TboiTrinkets;
import com.cozary.tboit.init.ModItems;
import com.cozary.tboit.init.ModLootTables;
import com.google.common.base.Preconditions;
import com.mojang.datafixers.util.Pair;
import net.minecraft.data.DataGenerator;
import net.minecraft.data.LootTableProvider;
import net.minecraft.item.Item;
import net.minecraft.loot.*;
import net.minecraft.resources.ResourcePackType;
import net.minecraft.util.ResourceLocation;
import net.minecraftforge.common.data.ExistingFileHelper;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Consumer;
import java.util.function.Supplier;

public class LootTables extends LootTableProvider {

    private final List<Pair<Supplier<Consumer<BiConsumer<ResourceLocation, LootTable.Builder>>>, LootParameterSet>> tables = new ArrayList<>();

    private final ExistingFileHelper existingFileHelper;

    public LootTables(DataGenerator dataGenerator, ExistingFileHelper existingFileHelper) {
        super(dataGenerator);
        this.existingFileHelper = existingFileHelper;
    }

    private static StandaloneLootEntry.Builder<?> createItemEntry(Item item, int weight) {
        return ItemLootEntry.builder(item).weight(weight);
    }

    @Override
    protected List<Pair<Supplier<Consumer<BiConsumer<ResourceLocation, LootTable.Builder>>>, LootParameterSet>> getTables() {
        tables.clear();
        addChestLootTables();

        return tables;
    }

    private void addChestLootTables() {
        for (String biome : Arrays.asList("desert", "plains", "savanna", "snowy", "taiga")) {
            addLootTable(
                    String.format("inject/chests/village/village_%s_house", biome),
                    LootTable.builder().addLootPool(
                            LootPool.builder()
                                    .name("main")
                                    .rolls(ConstantRange.of(1))
                                    .acceptCondition(ConfigurableRandomChance.configurableRandomChance(0.02F))
                                    .addEntry(createItemEntry(ModItems.AAA_BATTERY.get(), 1))
                                    .addEntry(createItemEntry(ModItems.ACE_OF_SPADES.get(), 1))
                                    .addEntry(createItemEntry(ModItems.A_MISSING_PAGE.get(), 1))
                                    .addEntry(createItemEntry(ModItems.BIBLE_TRACK.get(), 1))
                                    .addEntry(createItemEntry(ModItems.BLACK_LIPSTICK.get(), 1))
                                    .addEntry(createItemEntry(ModItems.BLOODY_PENNY.get(), 1))
                                    .addEntry(createItemEntry(ModItems.BLUE_BABY.get(), 1))
                                    .addEntry(createItemEntry(ModItems.BROKEN_ANKH.get(), 1))
                                    .addEntry(createItemEntry(ModItems.BROKEN_MAGNET.get(), 1))
                                    .addEntry(createItemEntry(ModItems.BROKEN_REMOTE.get(), 1))
                                    .addEntry(createItemEntry(ModItems.BURN_PENNY.get(), 1))
                                    .addEntry(createItemEntry(ModItems.BUTT_PENNY.get(), 1))
                                    .addEntry(createItemEntry(ModItems.CAINS_EYE.get(), 1))
                                    .addEntry(createItemEntry(ModItems.CALLUS.get(), 1))
                                    .addEntry(createItemEntry(ModItems.CANCER.get(), 1))
                                    .addEntry(createItemEntry(ModItems.CARTRIDGE.get(), 1))
                                    .addEntry(createItemEntry(ModItems.CHILDS_HEART.get(), 1))
                                    .addEntry(createItemEntry(ModItems.COUNTERFEIT_PENNY.get(), 1))
                                    .addEntry(createItemEntry(ModItems.CURSED_SKULL.get(), 1))
                                    .addEntry(createItemEntry(ModItems.CURVED_HORN.get(), 1))
                                    .addEntry(createItemEntry(ModItems.DAEMONS_TAIL.get(), 1))
                                    .addEntry(createItemEntry(ModItems.EVES_BIRD_FOOT.get(), 1))
                                    .addEntry(createItemEntry(ModItems.FISH_HEAD.get(), 1))
                                    .addEntry(createItemEntry(ModItems.FLAT_PENNY.get(), 1))
                                    .addEntry(createItemEntry(ModItems.FLAT_WORM.get(), 1))
                    )
            );
        }
        addLootTable("inject/chests/spawn_bonus_chest", LootTable.builder().addLootPool(
                        LootPool.builder()
                                .name("main")
                                .acceptCondition(ConfigurableRandomChance.configurableRandomChance(1))
                                .rolls(ConstantRange.of(1))
                                .addEntry(createItemEntry(ModItems.AAA_BATTERY.get(), 1))
                                .addEntry(createItemEntry(ModItems.ACE_OF_SPADES.get(), 1))
                                .addEntry(createItemEntry(ModItems.A_MISSING_PAGE.get(), 1))
                                .addEntry(createItemEntry(ModItems.BIBLE_TRACK.get(), 1))
                                .addEntry(createItemEntry(ModItems.BLACK_LIPSTICK.get(), 1))
                                .addEntry(createItemEntry(ModItems.BLOODY_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.BLUE_BABY.get(), 1))
                                .addEntry(createItemEntry(ModItems.BROKEN_ANKH.get(), 1))
                                .addEntry(createItemEntry(ModItems.BROKEN_MAGNET.get(), 1))
                                .addEntry(createItemEntry(ModItems.BROKEN_REMOTE.get(), 1))
                                .addEntry(createItemEntry(ModItems.BURN_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.BUTT_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.CAINS_EYE.get(), 1))
                                .addEntry(createItemEntry(ModItems.CALLUS.get(), 1))
                                .addEntry(createItemEntry(ModItems.CANCER.get(), 1))
                                .addEntry(createItemEntry(ModItems.CARTRIDGE.get(), 1))
                                .addEntry(createItemEntry(ModItems.CHILDS_HEART.get(), 1))
                                .addEntry(createItemEntry(ModItems.COUNTERFEIT_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.CURSED_SKULL.get(), 1))
                                .addEntry(createItemEntry(ModItems.CURVED_HORN.get(), 1))
                                .addEntry(createItemEntry(ModItems.DAEMONS_TAIL.get(), 1))
                                .addEntry(createItemEntry(ModItems.EVES_BIRD_FOOT.get(), 1))
                                .addEntry(createItemEntry(ModItems.FISH_HEAD.get(), 1))
                                .addEntry(createItemEntry(ModItems.FLAT_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.FLAT_WORM.get(), 1))                )
        );
        addLootTable("inject/chests/simple_dungeon", LootTable.builder().addLootPool(
                        LootPool.builder()
                                .name("main")
                                .acceptCondition(ConfigurableRandomChance.configurableRandomChance(0.1F))
                                .rolls(ConstantRange.of(1))
                                .addEntry(createItemEntry(ModItems.AAA_BATTERY.get(), 1))
                                .addEntry(createItemEntry(ModItems.ACE_OF_SPADES.get(), 1))
                                .addEntry(createItemEntry(ModItems.A_MISSING_PAGE.get(), 1))
                                .addEntry(createItemEntry(ModItems.BIBLE_TRACK.get(), 1))
                                .addEntry(createItemEntry(ModItems.BLACK_LIPSTICK.get(), 1))
                                .addEntry(createItemEntry(ModItems.BLOODY_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.BLUE_BABY.get(), 1))
                                .addEntry(createItemEntry(ModItems.BROKEN_ANKH.get(), 1))
                                .addEntry(createItemEntry(ModItems.BROKEN_MAGNET.get(), 1))
                                .addEntry(createItemEntry(ModItems.BROKEN_REMOTE.get(), 1))
                                .addEntry(createItemEntry(ModItems.BURN_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.BUTT_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.CAINS_EYE.get(), 1))
                                .addEntry(createItemEntry(ModItems.CALLUS.get(), 1))
                                .addEntry(createItemEntry(ModItems.CANCER.get(), 1))
                                .addEntry(createItemEntry(ModItems.CARTRIDGE.get(), 1))
                                .addEntry(createItemEntry(ModItems.CHILDS_HEART.get(), 1))
                                .addEntry(createItemEntry(ModItems.COUNTERFEIT_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.CURSED_SKULL.get(), 1))
                                .addEntry(createItemEntry(ModItems.CURVED_HORN.get(), 1))
                                .addEntry(createItemEntry(ModItems.DAEMONS_TAIL.get(), 1))
                                .addEntry(createItemEntry(ModItems.EVES_BIRD_FOOT.get(), 1))
                                .addEntry(createItemEntry(ModItems.FISH_HEAD.get(), 1))
                                .addEntry(createItemEntry(ModItems.FLAT_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.FLAT_WORM.get(), 1))                )
        );
        addLootTable("inject/chests/village/village_armorer", LootTable.builder().addLootPool(
                        LootPool.builder()
                                .name("main")
                                .rolls(ConstantRange.of(1))
                                .acceptCondition(ConfigurableRandomChance.configurableRandomChance(0.1F))
                                .addEntry(createItemEntry(ModItems.AAA_BATTERY.get(), 1))
                                .addEntry(createItemEntry(ModItems.ACE_OF_SPADES.get(), 1))
                                .addEntry(createItemEntry(ModItems.A_MISSING_PAGE.get(), 1))
                                .addEntry(createItemEntry(ModItems.BIBLE_TRACK.get(), 1))
                                .addEntry(createItemEntry(ModItems.BLACK_LIPSTICK.get(), 1))
                                .addEntry(createItemEntry(ModItems.BLOODY_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.BLUE_BABY.get(), 1))
                                .addEntry(createItemEntry(ModItems.BROKEN_ANKH.get(), 1))
                                .addEntry(createItemEntry(ModItems.BROKEN_MAGNET.get(), 1))
                                .addEntry(createItemEntry(ModItems.BROKEN_REMOTE.get(), 1))
                                .addEntry(createItemEntry(ModItems.BURN_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.BUTT_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.CAINS_EYE.get(), 1))
                                .addEntry(createItemEntry(ModItems.CALLUS.get(), 1))
                                .addEntry(createItemEntry(ModItems.CANCER.get(), 1))
                                .addEntry(createItemEntry(ModItems.CARTRIDGE.get(), 1))
                                .addEntry(createItemEntry(ModItems.CHILDS_HEART.get(), 1))
                                .addEntry(createItemEntry(ModItems.COUNTERFEIT_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.CURSED_SKULL.get(), 1))
                                .addEntry(createItemEntry(ModItems.CURVED_HORN.get(), 1))
                                .addEntry(createItemEntry(ModItems.DAEMONS_TAIL.get(), 1))
                                .addEntry(createItemEntry(ModItems.EVES_BIRD_FOOT.get(), 1))
                                .addEntry(createItemEntry(ModItems.FISH_HEAD.get(), 1))
                                .addEntry(createItemEntry(ModItems.FLAT_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.FLAT_WORM.get(), 1))
                )
        );
        addLootTable("inject/chests/village/village_butcher", LootTable.builder().addLootPool(
                        LootPool.builder()
                                .name("main")
                                .rolls(ConstantRange.of(1))
                                .acceptCondition(ConfigurableRandomChance.configurableRandomChance(0.02F))
                                .addEntry(createItemEntry(ModItems.AAA_BATTERY.get(), 1))
                                .addEntry(createItemEntry(ModItems.ACE_OF_SPADES.get(), 1))
                                .addEntry(createItemEntry(ModItems.A_MISSING_PAGE.get(), 1))
                                .addEntry(createItemEntry(ModItems.BIBLE_TRACK.get(), 1))
                                .addEntry(createItemEntry(ModItems.BLACK_LIPSTICK.get(), 1))
                                .addEntry(createItemEntry(ModItems.BLOODY_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.BLUE_BABY.get(), 1))
                                .addEntry(createItemEntry(ModItems.BROKEN_ANKH.get(), 1))
                                .addEntry(createItemEntry(ModItems.BROKEN_MAGNET.get(), 1))
                                .addEntry(createItemEntry(ModItems.BROKEN_REMOTE.get(), 1))
                                .addEntry(createItemEntry(ModItems.BURN_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.BUTT_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.CAINS_EYE.get(), 1))
                                .addEntry(createItemEntry(ModItems.CALLUS.get(), 1))
                                .addEntry(createItemEntry(ModItems.CANCER.get(), 1))
                                .addEntry(createItemEntry(ModItems.CARTRIDGE.get(), 1))
                                .addEntry(createItemEntry(ModItems.CHILDS_HEART.get(), 1))
                                .addEntry(createItemEntry(ModItems.COUNTERFEIT_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.CURSED_SKULL.get(), 1))
                                .addEntry(createItemEntry(ModItems.CURVED_HORN.get(), 1))
                                .addEntry(createItemEntry(ModItems.DAEMONS_TAIL.get(), 1))
                                .addEntry(createItemEntry(ModItems.EVES_BIRD_FOOT.get(), 1))
                                .addEntry(createItemEntry(ModItems.FISH_HEAD.get(), 1))
                                .addEntry(createItemEntry(ModItems.FLAT_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.FLAT_WORM.get(), 1))                )
        );
        addLootTable("inject/chests/village/village_tannery", LootTable.builder().addLootPool(
                        LootPool.builder()
                                .name("main")
                                .rolls(ConstantRange.of(1))
                                .acceptCondition(ConfigurableRandomChance.configurableRandomChance(0.2F))
                                .addEntry(createItemEntry(ModItems.AAA_BATTERY.get(), 1))
                                .addEntry(createItemEntry(ModItems.ACE_OF_SPADES.get(), 1))
                                .addEntry(createItemEntry(ModItems.A_MISSING_PAGE.get(), 1))
                                .addEntry(createItemEntry(ModItems.BIBLE_TRACK.get(), 1))
                                .addEntry(createItemEntry(ModItems.BLACK_LIPSTICK.get(), 1))
                                .addEntry(createItemEntry(ModItems.BLOODY_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.BLUE_BABY.get(), 1))
                                .addEntry(createItemEntry(ModItems.BROKEN_ANKH.get(), 1))
                                .addEntry(createItemEntry(ModItems.BROKEN_MAGNET.get(), 1))
                                .addEntry(createItemEntry(ModItems.BROKEN_REMOTE.get(), 1))
                                .addEntry(createItemEntry(ModItems.BURN_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.BUTT_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.CAINS_EYE.get(), 1))
                                .addEntry(createItemEntry(ModItems.CALLUS.get(), 1))
                                .addEntry(createItemEntry(ModItems.CANCER.get(), 1))
                                .addEntry(createItemEntry(ModItems.CARTRIDGE.get(), 1))
                                .addEntry(createItemEntry(ModItems.CHILDS_HEART.get(), 1))
                                .addEntry(createItemEntry(ModItems.COUNTERFEIT_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.CURSED_SKULL.get(), 1))
                                .addEntry(createItemEntry(ModItems.CURVED_HORN.get(), 1))
                                .addEntry(createItemEntry(ModItems.DAEMONS_TAIL.get(), 1))
                                .addEntry(createItemEntry(ModItems.EVES_BIRD_FOOT.get(), 1))
                                .addEntry(createItemEntry(ModItems.FISH_HEAD.get(), 1))
                                .addEntry(createItemEntry(ModItems.FLAT_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.FLAT_WORM.get(), 1))
                )
        );
        addLootTable("inject/chests/village/village_temple", LootTable.builder().addLootPool(
                        LootPool.builder()
                                .name("main")
                                .rolls(ConstantRange.of(1))
                                .acceptCondition(ConfigurableRandomChance.configurableRandomChance(0.2F))
                                .addEntry(createItemEntry(ModItems.AAA_BATTERY.get(), 1))
                                .addEntry(createItemEntry(ModItems.ACE_OF_SPADES.get(), 1))
                                .addEntry(createItemEntry(ModItems.A_MISSING_PAGE.get(), 1))
                                .addEntry(createItemEntry(ModItems.BIBLE_TRACK.get(), 1))
                                .addEntry(createItemEntry(ModItems.BLACK_LIPSTICK.get(), 1))
                                .addEntry(createItemEntry(ModItems.BLOODY_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.BLUE_BABY.get(), 1))
                                .addEntry(createItemEntry(ModItems.BROKEN_ANKH.get(), 1))
                                .addEntry(createItemEntry(ModItems.BROKEN_MAGNET.get(), 1))
                                .addEntry(createItemEntry(ModItems.BROKEN_REMOTE.get(), 1))
                                .addEntry(createItemEntry(ModItems.BURN_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.BUTT_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.CAINS_EYE.get(), 1))
                                .addEntry(createItemEntry(ModItems.CALLUS.get(), 1))
                                .addEntry(createItemEntry(ModItems.CANCER.get(), 1))
                                .addEntry(createItemEntry(ModItems.CARTRIDGE.get(), 1))
                                .addEntry(createItemEntry(ModItems.CHILDS_HEART.get(), 1))
                                .addEntry(createItemEntry(ModItems.COUNTERFEIT_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.CURSED_SKULL.get(), 1))
                                .addEntry(createItemEntry(ModItems.CURVED_HORN.get(), 1))
                                .addEntry(createItemEntry(ModItems.DAEMONS_TAIL.get(), 1))
                                .addEntry(createItemEntry(ModItems.EVES_BIRD_FOOT.get(), 1))
                                .addEntry(createItemEntry(ModItems.FISH_HEAD.get(), 1))
                                .addEntry(createItemEntry(ModItems.FLAT_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.FLAT_WORM.get(), 1))
                )
        );
        addLootTable("inject/chests/village/village_toolsmith", LootTable.builder().addLootPool(
                        LootPool.builder()
                                .name("main")
                                .rolls(ConstantRange.of(1))
                                .acceptCondition(ConfigurableRandomChance.configurableRandomChance(0.15F))
                                .addEntry(createItemEntry(ModItems.AAA_BATTERY.get(), 1))
                                .addEntry(createItemEntry(ModItems.ACE_OF_SPADES.get(), 1))
                                .addEntry(createItemEntry(ModItems.A_MISSING_PAGE.get(), 1))
                                .addEntry(createItemEntry(ModItems.BIBLE_TRACK.get(), 1))
                                .addEntry(createItemEntry(ModItems.BLACK_LIPSTICK.get(), 1))
                                .addEntry(createItemEntry(ModItems.BLOODY_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.BLUE_BABY.get(), 1))
                                .addEntry(createItemEntry(ModItems.BROKEN_ANKH.get(), 1))
                                .addEntry(createItemEntry(ModItems.BROKEN_MAGNET.get(), 1))
                                .addEntry(createItemEntry(ModItems.BROKEN_REMOTE.get(), 1))
                                .addEntry(createItemEntry(ModItems.BURN_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.BUTT_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.CAINS_EYE.get(), 1))
                                .addEntry(createItemEntry(ModItems.CALLUS.get(), 1))
                                .addEntry(createItemEntry(ModItems.CANCER.get(), 1))
                                .addEntry(createItemEntry(ModItems.CARTRIDGE.get(), 1))
                                .addEntry(createItemEntry(ModItems.CHILDS_HEART.get(), 1))
                                .addEntry(createItemEntry(ModItems.COUNTERFEIT_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.CURSED_SKULL.get(), 1))
                                .addEntry(createItemEntry(ModItems.CURVED_HORN.get(), 1))
                                .addEntry(createItemEntry(ModItems.DAEMONS_TAIL.get(), 1))
                                .addEntry(createItemEntry(ModItems.EVES_BIRD_FOOT.get(), 1))
                                .addEntry(createItemEntry(ModItems.FISH_HEAD.get(), 1))
                                .addEntry(createItemEntry(ModItems.FLAT_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.FLAT_WORM.get(), 1))
                )
        );
        addLootTable("inject/chests/village/village_weaponsmith", LootTable.builder().addLootPool(
                        LootPool.builder()
                                .name("main")
                                .rolls(ConstantRange.of(1))
                                .acceptCondition(ConfigurableRandomChance.configurableRandomChance(0.1F))
                                .addEntry(createItemEntry(ModItems.AAA_BATTERY.get(), 1))
                                .addEntry(createItemEntry(ModItems.ACE_OF_SPADES.get(), 1))
                                .addEntry(createItemEntry(ModItems.A_MISSING_PAGE.get(), 1))
                                .addEntry(createItemEntry(ModItems.BIBLE_TRACK.get(), 1))
                                .addEntry(createItemEntry(ModItems.BLACK_LIPSTICK.get(), 1))
                                .addEntry(createItemEntry(ModItems.BLOODY_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.BLUE_BABY.get(), 1))
                                .addEntry(createItemEntry(ModItems.BROKEN_ANKH.get(), 1))
                                .addEntry(createItemEntry(ModItems.BROKEN_MAGNET.get(), 1))
                                .addEntry(createItemEntry(ModItems.BROKEN_REMOTE.get(), 1))
                                .addEntry(createItemEntry(ModItems.BURN_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.BUTT_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.CAINS_EYE.get(), 1))
                                .addEntry(createItemEntry(ModItems.CALLUS.get(), 1))
                                .addEntry(createItemEntry(ModItems.CANCER.get(), 1))
                                .addEntry(createItemEntry(ModItems.CARTRIDGE.get(), 1))
                                .addEntry(createItemEntry(ModItems.CHILDS_HEART.get(), 1))
                                .addEntry(createItemEntry(ModItems.COUNTERFEIT_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.CURSED_SKULL.get(), 1))
                                .addEntry(createItemEntry(ModItems.CURVED_HORN.get(), 1))
                                .addEntry(createItemEntry(ModItems.DAEMONS_TAIL.get(), 1))
                                .addEntry(createItemEntry(ModItems.EVES_BIRD_FOOT.get(), 1))
                                .addEntry(createItemEntry(ModItems.FISH_HEAD.get(), 1))
                                .addEntry(createItemEntry(ModItems.FLAT_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.FLAT_WORM.get(), 1))
                )
        );
        addLootTable("inject/chests/abandoned_mineshaft", LootTable.builder().addLootPool(
                        LootPool.builder()
                                .name("main")
                                .rolls(ConstantRange.of(1))
                                .acceptCondition(ConfigurableRandomChance.configurableRandomChance(0.30F))
                                .addEntry(createItemEntry(ModItems.AAA_BATTERY.get(), 1))
                                .addEntry(createItemEntry(ModItems.ACE_OF_SPADES.get(), 1))
                                .addEntry(createItemEntry(ModItems.A_MISSING_PAGE.get(), 1))
                                .addEntry(createItemEntry(ModItems.BIBLE_TRACK.get(), 1))
                                .addEntry(createItemEntry(ModItems.BLACK_LIPSTICK.get(), 1))
                                .addEntry(createItemEntry(ModItems.BLOODY_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.BLUE_BABY.get(), 1))
                                .addEntry(createItemEntry(ModItems.BROKEN_ANKH.get(), 1))
                                .addEntry(createItemEntry(ModItems.BROKEN_MAGNET.get(), 1))
                                .addEntry(createItemEntry(ModItems.BROKEN_REMOTE.get(), 1))
                                .addEntry(createItemEntry(ModItems.BURN_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.BUTT_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.CAINS_EYE.get(), 1))
                                .addEntry(createItemEntry(ModItems.CALLUS.get(), 1))
                                .addEntry(createItemEntry(ModItems.CANCER.get(), 1))
                                .addEntry(createItemEntry(ModItems.CARTRIDGE.get(), 1))
                                .addEntry(createItemEntry(ModItems.CHILDS_HEART.get(), 1))
                                .addEntry(createItemEntry(ModItems.COUNTERFEIT_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.CURSED_SKULL.get(), 1))
                                .addEntry(createItemEntry(ModItems.CURVED_HORN.get(), 1))
                                .addEntry(createItemEntry(ModItems.DAEMONS_TAIL.get(), 1))
                                .addEntry(createItemEntry(ModItems.EVES_BIRD_FOOT.get(), 1))
                                .addEntry(createItemEntry(ModItems.FISH_HEAD.get(), 1))
                                .addEntry(createItemEntry(ModItems.FLAT_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.FLAT_WORM.get(), 1))
                )
        );
        addLootTable("inject/chests/bastion_hoglin_stable", LootTable.builder().addLootPool(
                        LootPool.builder()
                                .name("main")
                                .rolls(ConstantRange.of(1))
                                .acceptCondition(ConfigurableRandomChance.configurableRandomChance(0.20F))
                                .addEntry(createItemEntry(ModItems.AAA_BATTERY.get(), 1))
                                .addEntry(createItemEntry(ModItems.ACE_OF_SPADES.get(), 1))
                                .addEntry(createItemEntry(ModItems.A_MISSING_PAGE.get(), 1))
                                .addEntry(createItemEntry(ModItems.BIBLE_TRACK.get(), 1))
                                .addEntry(createItemEntry(ModItems.BLACK_LIPSTICK.get(), 1))
                                .addEntry(createItemEntry(ModItems.BLOODY_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.BLUE_BABY.get(), 1))
                                .addEntry(createItemEntry(ModItems.BROKEN_ANKH.get(), 1))
                                .addEntry(createItemEntry(ModItems.BROKEN_MAGNET.get(), 1))
                                .addEntry(createItemEntry(ModItems.BROKEN_REMOTE.get(), 1))
                                .addEntry(createItemEntry(ModItems.BURN_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.BUTT_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.CAINS_EYE.get(), 1))
                                .addEntry(createItemEntry(ModItems.CALLUS.get(), 1))
                                .addEntry(createItemEntry(ModItems.CANCER.get(), 1))
                                .addEntry(createItemEntry(ModItems.CARTRIDGE.get(), 1))
                                .addEntry(createItemEntry(ModItems.CHILDS_HEART.get(), 1))
                                .addEntry(createItemEntry(ModItems.COUNTERFEIT_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.CURSED_SKULL.get(), 1))
                                .addEntry(createItemEntry(ModItems.CURVED_HORN.get(), 1))
                                .addEntry(createItemEntry(ModItems.DAEMONS_TAIL.get(), 1))
                                .addEntry(createItemEntry(ModItems.EVES_BIRD_FOOT.get(), 1))
                                .addEntry(createItemEntry(ModItems.FISH_HEAD.get(), 1))
                                .addEntry(createItemEntry(ModItems.FLAT_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.FLAT_WORM.get(), 1))
                )
        );
        addLootTable("inject/chests/bastion_treasure", LootTable.builder().addLootPool(
                        LootPool.builder()
                                .name("main")
                                .rolls(ConstantRange.of(1))
                                .acceptCondition(ConfigurableRandomChance.configurableRandomChance(0.65F))
                                .addEntry(createItemEntry(ModItems.AAA_BATTERY.get(), 1))
                                .addEntry(createItemEntry(ModItems.ACE_OF_SPADES.get(), 1))
                                .addEntry(createItemEntry(ModItems.A_MISSING_PAGE.get(), 1))
                                .addEntry(createItemEntry(ModItems.BIBLE_TRACK.get(), 1))
                                .addEntry(createItemEntry(ModItems.BLACK_LIPSTICK.get(), 1))
                                .addEntry(createItemEntry(ModItems.BLOODY_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.BLUE_BABY.get(), 1))
                                .addEntry(createItemEntry(ModItems.BROKEN_ANKH.get(), 1))
                                .addEntry(createItemEntry(ModItems.BROKEN_MAGNET.get(), 1))
                                .addEntry(createItemEntry(ModItems.BROKEN_REMOTE.get(), 1))
                                .addEntry(createItemEntry(ModItems.BURN_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.BUTT_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.CAINS_EYE.get(), 1))
                                .addEntry(createItemEntry(ModItems.CALLUS.get(), 1))
                                .addEntry(createItemEntry(ModItems.CANCER.get(), 1))
                                .addEntry(createItemEntry(ModItems.CARTRIDGE.get(), 1))
                                .addEntry(createItemEntry(ModItems.CHILDS_HEART.get(), 1))
                                .addEntry(createItemEntry(ModItems.COUNTERFEIT_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.CURSED_SKULL.get(), 1))
                                .addEntry(createItemEntry(ModItems.CURVED_HORN.get(), 1))
                                .addEntry(createItemEntry(ModItems.DAEMONS_TAIL.get(), 1))
                                .addEntry(createItemEntry(ModItems.EVES_BIRD_FOOT.get(), 1))
                                .addEntry(createItemEntry(ModItems.FISH_HEAD.get(), 1))
                                .addEntry(createItemEntry(ModItems.FLAT_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.FLAT_WORM.get(), 1))
                )
        );
        addLootTable("inject/chests/buried_treasure", LootTable.builder().addLootPool(
                        LootPool.builder()
                                .name("main")
                                .rolls(ConstantRange.of(1))
                                .acceptCondition(ConfigurableRandomChance.configurableRandomChance(0.25F))
                                .addEntry(createItemEntry(ModItems.AAA_BATTERY.get(), 1))
                                .addEntry(createItemEntry(ModItems.ACE_OF_SPADES.get(), 1))
                                .addEntry(createItemEntry(ModItems.A_MISSING_PAGE.get(), 1))
                                .addEntry(createItemEntry(ModItems.BIBLE_TRACK.get(), 1))
                                .addEntry(createItemEntry(ModItems.BLACK_LIPSTICK.get(), 1))
                                .addEntry(createItemEntry(ModItems.BLOODY_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.BLUE_BABY.get(), 1))
                                .addEntry(createItemEntry(ModItems.BROKEN_ANKH.get(), 1))
                                .addEntry(createItemEntry(ModItems.BROKEN_MAGNET.get(), 1))
                                .addEntry(createItemEntry(ModItems.BROKEN_REMOTE.get(), 1))
                                .addEntry(createItemEntry(ModItems.BURN_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.BUTT_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.CAINS_EYE.get(), 1))
                                .addEntry(createItemEntry(ModItems.CALLUS.get(), 1))
                                .addEntry(createItemEntry(ModItems.CANCER.get(), 1))
                                .addEntry(createItemEntry(ModItems.CARTRIDGE.get(), 1))
                                .addEntry(createItemEntry(ModItems.CHILDS_HEART.get(), 1))
                                .addEntry(createItemEntry(ModItems.COUNTERFEIT_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.CURSED_SKULL.get(), 1))
                                .addEntry(createItemEntry(ModItems.CURVED_HORN.get(), 1))
                                .addEntry(createItemEntry(ModItems.DAEMONS_TAIL.get(), 1))
                                .addEntry(createItemEntry(ModItems.EVES_BIRD_FOOT.get(), 1))
                                .addEntry(createItemEntry(ModItems.FISH_HEAD.get(), 1))
                                .addEntry(createItemEntry(ModItems.FLAT_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.FLAT_WORM.get(), 1))
                )
        );
        addLootTable("inject/chests/desert_pyramid", LootTable.builder().addLootPool(
                        LootPool.builder()
                                .name("main")
                                .rolls(ConstantRange.of(1))
                                .acceptCondition(ConfigurableRandomChance.configurableRandomChance(0.2F))
                                .addEntry(createItemEntry(ModItems.AAA_BATTERY.get(), 1))
                                .addEntry(createItemEntry(ModItems.ACE_OF_SPADES.get(), 1))
                                .addEntry(createItemEntry(ModItems.A_MISSING_PAGE.get(), 1))
                                .addEntry(createItemEntry(ModItems.BIBLE_TRACK.get(), 1))
                                .addEntry(createItemEntry(ModItems.BLACK_LIPSTICK.get(), 1))
                                .addEntry(createItemEntry(ModItems.BLOODY_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.BLUE_BABY.get(), 1))
                                .addEntry(createItemEntry(ModItems.BROKEN_ANKH.get(), 1))
                                .addEntry(createItemEntry(ModItems.BROKEN_MAGNET.get(), 1))
                                .addEntry(createItemEntry(ModItems.BROKEN_REMOTE.get(), 1))
                                .addEntry(createItemEntry(ModItems.BURN_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.BUTT_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.CAINS_EYE.get(), 1))
                                .addEntry(createItemEntry(ModItems.CALLUS.get(), 1))
                                .addEntry(createItemEntry(ModItems.CANCER.get(), 1))
                                .addEntry(createItemEntry(ModItems.CARTRIDGE.get(), 1))
                                .addEntry(createItemEntry(ModItems.CHILDS_HEART.get(), 1))
                                .addEntry(createItemEntry(ModItems.COUNTERFEIT_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.CURSED_SKULL.get(), 1))
                                .addEntry(createItemEntry(ModItems.CURVED_HORN.get(), 1))
                                .addEntry(createItemEntry(ModItems.DAEMONS_TAIL.get(), 1))
                                .addEntry(createItemEntry(ModItems.EVES_BIRD_FOOT.get(), 1))
                                .addEntry(createItemEntry(ModItems.FISH_HEAD.get(), 1))
                                .addEntry(createItemEntry(ModItems.FLAT_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.FLAT_WORM.get(), 1))
                )
        );
        addLootTable("inject/chests/end_city_treasure", LootTable.builder().addLootPool(
                        LootPool.builder()
                                .name("main")
                                .rolls(ConstantRange.of(1))
                                .acceptCondition(ConfigurableRandomChance.configurableRandomChance(0.3F))
                                .addEntry(createItemEntry(ModItems.AAA_BATTERY.get(), 1))
                                .addEntry(createItemEntry(ModItems.ACE_OF_SPADES.get(), 1))
                                .addEntry(createItemEntry(ModItems.A_MISSING_PAGE.get(), 1))
                                .addEntry(createItemEntry(ModItems.BIBLE_TRACK.get(), 1))
                                .addEntry(createItemEntry(ModItems.BLACK_LIPSTICK.get(), 1))
                                .addEntry(createItemEntry(ModItems.BLOODY_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.BLUE_BABY.get(), 1))
                                .addEntry(createItemEntry(ModItems.BROKEN_ANKH.get(), 1))
                                .addEntry(createItemEntry(ModItems.BROKEN_MAGNET.get(), 1))
                                .addEntry(createItemEntry(ModItems.BROKEN_REMOTE.get(), 1))
                                .addEntry(createItemEntry(ModItems.BURN_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.BUTT_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.CAINS_EYE.get(), 1))
                                .addEntry(createItemEntry(ModItems.CALLUS.get(), 1))
                                .addEntry(createItemEntry(ModItems.CANCER.get(), 1))
                                .addEntry(createItemEntry(ModItems.CARTRIDGE.get(), 1))
                                .addEntry(createItemEntry(ModItems.CHILDS_HEART.get(), 1))
                                .addEntry(createItemEntry(ModItems.COUNTERFEIT_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.CURSED_SKULL.get(), 1))
                                .addEntry(createItemEntry(ModItems.CURVED_HORN.get(), 1))
                                .addEntry(createItemEntry(ModItems.DAEMONS_TAIL.get(), 1))
                                .addEntry(createItemEntry(ModItems.EVES_BIRD_FOOT.get(), 1))
                                .addEntry(createItemEntry(ModItems.FISH_HEAD.get(), 1))
                                .addEntry(createItemEntry(ModItems.FLAT_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.FLAT_WORM.get(), 1))
                )
        );
        addLootTable("inject/chests/jungle_temple", LootTable.builder().addLootPool(
                        LootPool.builder()
                                .name("main")
                                .rolls(ConstantRange.of(1))
                                .acceptCondition(ConfigurableRandomChance.configurableRandomChance(0.3F))
                                .addEntry(createItemEntry(ModItems.AAA_BATTERY.get(), 1))
                                .addEntry(createItemEntry(ModItems.ACE_OF_SPADES.get(), 1))
                                .addEntry(createItemEntry(ModItems.A_MISSING_PAGE.get(), 1))
                                .addEntry(createItemEntry(ModItems.BIBLE_TRACK.get(), 1))
                                .addEntry(createItemEntry(ModItems.BLACK_LIPSTICK.get(), 1))
                                .addEntry(createItemEntry(ModItems.BLOODY_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.BLUE_BABY.get(), 1))
                                .addEntry(createItemEntry(ModItems.BROKEN_ANKH.get(), 1))
                                .addEntry(createItemEntry(ModItems.BROKEN_MAGNET.get(), 1))
                                .addEntry(createItemEntry(ModItems.BROKEN_REMOTE.get(), 1))
                                .addEntry(createItemEntry(ModItems.BURN_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.BUTT_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.CAINS_EYE.get(), 1))
                                .addEntry(createItemEntry(ModItems.CALLUS.get(), 1))
                                .addEntry(createItemEntry(ModItems.CANCER.get(), 1))
                                .addEntry(createItemEntry(ModItems.CARTRIDGE.get(), 1))
                                .addEntry(createItemEntry(ModItems.CHILDS_HEART.get(), 1))
                                .addEntry(createItemEntry(ModItems.COUNTERFEIT_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.CURSED_SKULL.get(), 1))
                                .addEntry(createItemEntry(ModItems.CURVED_HORN.get(), 1))
                                .addEntry(createItemEntry(ModItems.DAEMONS_TAIL.get(), 1))
                                .addEntry(createItemEntry(ModItems.EVES_BIRD_FOOT.get(), 1))
                                .addEntry(createItemEntry(ModItems.FISH_HEAD.get(), 1))
                                .addEntry(createItemEntry(ModItems.FLAT_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.FLAT_WORM.get(), 1))
                )
        );
        addLootTable("inject/chests/nether_bridge", LootTable.builder().addLootPool(
                        LootPool.builder()
                                .name("main")
                                .rolls(ConstantRange.of(1))
                                .acceptCondition(ConfigurableRandomChance.configurableRandomChance(0.15F))
                                .addEntry(createItemEntry(ModItems.AAA_BATTERY.get(), 1))
                                .addEntry(createItemEntry(ModItems.ACE_OF_SPADES.get(), 1))
                                .addEntry(createItemEntry(ModItems.A_MISSING_PAGE.get(), 1))
                                .addEntry(createItemEntry(ModItems.BIBLE_TRACK.get(), 1))
                                .addEntry(createItemEntry(ModItems.BLACK_LIPSTICK.get(), 1))
                                .addEntry(createItemEntry(ModItems.BLOODY_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.BLUE_BABY.get(), 1))
                                .addEntry(createItemEntry(ModItems.BROKEN_ANKH.get(), 1))
                                .addEntry(createItemEntry(ModItems.BROKEN_MAGNET.get(), 1))
                                .addEntry(createItemEntry(ModItems.BROKEN_REMOTE.get(), 1))
                                .addEntry(createItemEntry(ModItems.BURN_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.BUTT_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.CAINS_EYE.get(), 1))
                                .addEntry(createItemEntry(ModItems.CALLUS.get(), 1))
                                .addEntry(createItemEntry(ModItems.CANCER.get(), 1))
                                .addEntry(createItemEntry(ModItems.CARTRIDGE.get(), 1))
                                .addEntry(createItemEntry(ModItems.CHILDS_HEART.get(), 1))
                                .addEntry(createItemEntry(ModItems.COUNTERFEIT_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.CURSED_SKULL.get(), 1))
                                .addEntry(createItemEntry(ModItems.CURVED_HORN.get(), 1))
                                .addEntry(createItemEntry(ModItems.DAEMONS_TAIL.get(), 1))
                                .addEntry(createItemEntry(ModItems.EVES_BIRD_FOOT.get(), 1))
                                .addEntry(createItemEntry(ModItems.FISH_HEAD.get(), 1))
                                .addEntry(createItemEntry(ModItems.FLAT_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.FLAT_WORM.get(), 1))
                )
        );
        addLootTable("inject/chests/pillager_outpost", LootTable.builder().addLootPool(
                        LootPool.builder()
                                .name("main")
                                .rolls(ConstantRange.of(1))
                                .acceptCondition(ConfigurableRandomChance.configurableRandomChance(0.25F))
                                .addEntry(createItemEntry(ModItems.AAA_BATTERY.get(), 1))
                                .addEntry(createItemEntry(ModItems.ACE_OF_SPADES.get(), 1))
                                .addEntry(createItemEntry(ModItems.A_MISSING_PAGE.get(), 1))
                                .addEntry(createItemEntry(ModItems.BIBLE_TRACK.get(), 1))
                                .addEntry(createItemEntry(ModItems.BLACK_LIPSTICK.get(), 1))
                                .addEntry(createItemEntry(ModItems.BLOODY_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.BLUE_BABY.get(), 1))
                                .addEntry(createItemEntry(ModItems.BROKEN_ANKH.get(), 1))
                                .addEntry(createItemEntry(ModItems.BROKEN_MAGNET.get(), 1))
                                .addEntry(createItemEntry(ModItems.BROKEN_REMOTE.get(), 1))
                                .addEntry(createItemEntry(ModItems.BURN_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.BUTT_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.CAINS_EYE.get(), 1))
                                .addEntry(createItemEntry(ModItems.CALLUS.get(), 1))
                                .addEntry(createItemEntry(ModItems.CANCER.get(), 1))
                                .addEntry(createItemEntry(ModItems.CARTRIDGE.get(), 1))
                                .addEntry(createItemEntry(ModItems.CHILDS_HEART.get(), 1))
                                .addEntry(createItemEntry(ModItems.COUNTERFEIT_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.CURSED_SKULL.get(), 1))
                                .addEntry(createItemEntry(ModItems.CURVED_HORN.get(), 1))
                                .addEntry(createItemEntry(ModItems.DAEMONS_TAIL.get(), 1))
                                .addEntry(createItemEntry(ModItems.EVES_BIRD_FOOT.get(), 1))
                                .addEntry(createItemEntry(ModItems.FISH_HEAD.get(), 1))
                                .addEntry(createItemEntry(ModItems.FLAT_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.FLAT_WORM.get(), 1))
                )
        );
        addLootTable("inject/chests/ruined_portal", LootTable.builder().addLootPool(
                        LootPool.builder()
                                .name("main")
                                .rolls(ConstantRange.of(1))
                                .acceptCondition(ConfigurableRandomChance.configurableRandomChance(0.15F))
                                .addEntry(createItemEntry(ModItems.AAA_BATTERY.get(), 1))
                                .addEntry(createItemEntry(ModItems.ACE_OF_SPADES.get(), 1))
                                .addEntry(createItemEntry(ModItems.A_MISSING_PAGE.get(), 1))
                                .addEntry(createItemEntry(ModItems.BIBLE_TRACK.get(), 1))
                                .addEntry(createItemEntry(ModItems.BLACK_LIPSTICK.get(), 1))
                                .addEntry(createItemEntry(ModItems.BLOODY_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.BLUE_BABY.get(), 1))
                                .addEntry(createItemEntry(ModItems.BROKEN_ANKH.get(), 1))
                                .addEntry(createItemEntry(ModItems.BROKEN_MAGNET.get(), 1))
                                .addEntry(createItemEntry(ModItems.BROKEN_REMOTE.get(), 1))
                                .addEntry(createItemEntry(ModItems.BURN_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.BUTT_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.CAINS_EYE.get(), 1))
                                .addEntry(createItemEntry(ModItems.CALLUS.get(), 1))
                                .addEntry(createItemEntry(ModItems.CANCER.get(), 1))
                                .addEntry(createItemEntry(ModItems.CARTRIDGE.get(), 1))
                                .addEntry(createItemEntry(ModItems.CHILDS_HEART.get(), 1))
                                .addEntry(createItemEntry(ModItems.COUNTERFEIT_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.CURSED_SKULL.get(), 1))
                                .addEntry(createItemEntry(ModItems.CURVED_HORN.get(), 1))
                                .addEntry(createItemEntry(ModItems.DAEMONS_TAIL.get(), 1))
                                .addEntry(createItemEntry(ModItems.EVES_BIRD_FOOT.get(), 1))
                                .addEntry(createItemEntry(ModItems.FISH_HEAD.get(), 1))
                                .addEntry(createItemEntry(ModItems.FLAT_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.FLAT_WORM.get(), 1))
                )
        );
        addLootTable("inject/chests/shipwreck_treasure", LootTable.builder().addLootPool(
                        LootPool.builder()
                                .name("main")
                                .rolls(ConstantRange.of(1))
                                .acceptCondition(ConfigurableRandomChance.configurableRandomChance(0.15F))
                                .addEntry(createItemEntry(ModItems.AAA_BATTERY.get(), 1))
                                .addEntry(createItemEntry(ModItems.ACE_OF_SPADES.get(), 1))
                                .addEntry(createItemEntry(ModItems.A_MISSING_PAGE.get(), 1))
                                .addEntry(createItemEntry(ModItems.BIBLE_TRACK.get(), 1))
                                .addEntry(createItemEntry(ModItems.BLACK_LIPSTICK.get(), 1))
                                .addEntry(createItemEntry(ModItems.BLOODY_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.BLUE_BABY.get(), 1))
                                .addEntry(createItemEntry(ModItems.BROKEN_ANKH.get(), 1))
                                .addEntry(createItemEntry(ModItems.BROKEN_MAGNET.get(), 1))
                                .addEntry(createItemEntry(ModItems.BROKEN_REMOTE.get(), 1))
                                .addEntry(createItemEntry(ModItems.BURN_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.BUTT_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.CAINS_EYE.get(), 1))
                                .addEntry(createItemEntry(ModItems.CALLUS.get(), 1))
                                .addEntry(createItemEntry(ModItems.CANCER.get(), 1))
                                .addEntry(createItemEntry(ModItems.CARTRIDGE.get(), 1))
                                .addEntry(createItemEntry(ModItems.CHILDS_HEART.get(), 1))
                                .addEntry(createItemEntry(ModItems.COUNTERFEIT_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.CURSED_SKULL.get(), 1))
                                .addEntry(createItemEntry(ModItems.CURVED_HORN.get(), 1))
                                .addEntry(createItemEntry(ModItems.DAEMONS_TAIL.get(), 1))
                                .addEntry(createItemEntry(ModItems.EVES_BIRD_FOOT.get(), 1))
                                .addEntry(createItemEntry(ModItems.FISH_HEAD.get(), 1))
                                .addEntry(createItemEntry(ModItems.FLAT_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.FLAT_WORM.get(), 1))
                )
        );
        addLootTable("inject/chests/stronghold_corridor", LootTable.builder().addLootPool(
                        LootPool.builder()
                                .name("main")
                                .rolls(ConstantRange.of(1))
                                .acceptCondition(ConfigurableRandomChance.configurableRandomChance(0.3F))
                                .addEntry(createItemEntry(ModItems.AAA_BATTERY.get(), 1))
                                .addEntry(createItemEntry(ModItems.ACE_OF_SPADES.get(), 1))
                                .addEntry(createItemEntry(ModItems.A_MISSING_PAGE.get(), 1))
                                .addEntry(createItemEntry(ModItems.BIBLE_TRACK.get(), 1))
                                .addEntry(createItemEntry(ModItems.BLACK_LIPSTICK.get(), 1))
                                .addEntry(createItemEntry(ModItems.BLOODY_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.BLUE_BABY.get(), 1))
                                .addEntry(createItemEntry(ModItems.BROKEN_ANKH.get(), 1))
                                .addEntry(createItemEntry(ModItems.BROKEN_MAGNET.get(), 1))
                                .addEntry(createItemEntry(ModItems.BROKEN_REMOTE.get(), 1))
                                .addEntry(createItemEntry(ModItems.BURN_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.BUTT_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.CAINS_EYE.get(), 1))
                                .addEntry(createItemEntry(ModItems.CALLUS.get(), 1))
                                .addEntry(createItemEntry(ModItems.CANCER.get(), 1))
                                .addEntry(createItemEntry(ModItems.CARTRIDGE.get(), 1))
                                .addEntry(createItemEntry(ModItems.CHILDS_HEART.get(), 1))
                                .addEntry(createItemEntry(ModItems.COUNTERFEIT_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.CURSED_SKULL.get(), 1))
                                .addEntry(createItemEntry(ModItems.CURVED_HORN.get(), 1))
                                .addEntry(createItemEntry(ModItems.DAEMONS_TAIL.get(), 1))
                                .addEntry(createItemEntry(ModItems.EVES_BIRD_FOOT.get(), 1))
                                .addEntry(createItemEntry(ModItems.FISH_HEAD.get(), 1))
                                .addEntry(createItemEntry(ModItems.FLAT_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.FLAT_WORM.get(), 1))
                )
        );
        addLootTable("inject/chests/underwater_ruin_big", LootTable.builder().addLootPool(
                        LootPool.builder()
                                .name("main")
                                .rolls(ConstantRange.of(1))
                                .acceptCondition(ConfigurableRandomChance.configurableRandomChance(0.45F))
                                .addEntry(createItemEntry(ModItems.AAA_BATTERY.get(), 1))
                                .addEntry(createItemEntry(ModItems.ACE_OF_SPADES.get(), 1))
                                .addEntry(createItemEntry(ModItems.A_MISSING_PAGE.get(), 1))
                                .addEntry(createItemEntry(ModItems.BIBLE_TRACK.get(), 1))
                                .addEntry(createItemEntry(ModItems.BLACK_LIPSTICK.get(), 1))
                                .addEntry(createItemEntry(ModItems.BLOODY_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.BLUE_BABY.get(), 1))
                                .addEntry(createItemEntry(ModItems.BROKEN_ANKH.get(), 1))
                                .addEntry(createItemEntry(ModItems.BROKEN_MAGNET.get(), 1))
                                .addEntry(createItemEntry(ModItems.BROKEN_REMOTE.get(), 1))
                                .addEntry(createItemEntry(ModItems.BURN_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.BUTT_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.CAINS_EYE.get(), 1))
                                .addEntry(createItemEntry(ModItems.CALLUS.get(), 1))
                                .addEntry(createItemEntry(ModItems.CANCER.get(), 1))
                                .addEntry(createItemEntry(ModItems.CARTRIDGE.get(), 1))
                                .addEntry(createItemEntry(ModItems.CHILDS_HEART.get(), 1))
                                .addEntry(createItemEntry(ModItems.COUNTERFEIT_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.CURSED_SKULL.get(), 1))
                                .addEntry(createItemEntry(ModItems.CURVED_HORN.get(), 1))
                                .addEntry(createItemEntry(ModItems.DAEMONS_TAIL.get(), 1))
                                .addEntry(createItemEntry(ModItems.EVES_BIRD_FOOT.get(), 1))
                                .addEntry(createItemEntry(ModItems.FISH_HEAD.get(), 1))
                                .addEntry(createItemEntry(ModItems.FLAT_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.FLAT_WORM.get(), 1))
                )
        );
        addLootTable("inject/chests/woodland_mansion", LootTable.builder().addLootPool(
                        LootPool.builder()
                                .name("main")
                                .rolls(ConstantRange.of(1))
                                .acceptCondition(ConfigurableRandomChance.configurableRandomChance(0.25F))
                                .addEntry(createItemEntry(ModItems.AAA_BATTERY.get(), 1))
                                .addEntry(createItemEntry(ModItems.ACE_OF_SPADES.get(), 1))
                                .addEntry(createItemEntry(ModItems.A_MISSING_PAGE.get(), 1))
                                .addEntry(createItemEntry(ModItems.BIBLE_TRACK.get(), 1))
                                .addEntry(createItemEntry(ModItems.BLACK_LIPSTICK.get(), 1))
                                .addEntry(createItemEntry(ModItems.BLOODY_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.BLUE_BABY.get(), 1))
                                .addEntry(createItemEntry(ModItems.BROKEN_ANKH.get(), 1))
                                .addEntry(createItemEntry(ModItems.BROKEN_MAGNET.get(), 1))
                                .addEntry(createItemEntry(ModItems.BROKEN_REMOTE.get(), 1))
                                .addEntry(createItemEntry(ModItems.BURN_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.BUTT_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.CAINS_EYE.get(), 1))
                                .addEntry(createItemEntry(ModItems.CALLUS.get(), 1))
                                .addEntry(createItemEntry(ModItems.CANCER.get(), 1))
                                .addEntry(createItemEntry(ModItems.CARTRIDGE.get(), 1))
                                .addEntry(createItemEntry(ModItems.CHILDS_HEART.get(), 1))
                                .addEntry(createItemEntry(ModItems.COUNTERFEIT_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.CURSED_SKULL.get(), 1))
                                .addEntry(createItemEntry(ModItems.CURVED_HORN.get(), 1))
                                .addEntry(createItemEntry(ModItems.DAEMONS_TAIL.get(), 1))
                                .addEntry(createItemEntry(ModItems.EVES_BIRD_FOOT.get(), 1))
                                .addEntry(createItemEntry(ModItems.FISH_HEAD.get(), 1))
                                .addEntry(createItemEntry(ModItems.FLAT_PENNY.get(), 1))
                                .addEntry(createItemEntry(ModItems.FLAT_WORM.get(), 1))                )
        );
    }

    private void addLootTable(String location, LootTable.Builder lootTable, LootParameterSet lootParameterSet) {
        if (location.startsWith("inject/")) {
            String actualLocation = location.replace("inject/", "");
            Preconditions.checkArgument(existingFileHelper.exists(new ResourceLocation("loot_tables/" + actualLocation + ".json"), ResourcePackType.SERVER_DATA), "Loot table %s does not exist", actualLocation);
            Preconditions.checkArgument(ModLootTables.LootTableEvents.LOOT_TABLE_LOCATIONS.contains(actualLocation), "Loot table %s does not exist", actualLocation);
        }
        tables.add(Pair.of(() -> lootBuilder -> lootBuilder.accept(new ResourceLocation(TboiTrinkets.MOD_ID, location), lootTable), lootParameterSet));
    }

    private void addLootTable(String location, LootTable.Builder lootTable) {
        addLootTable(location, lootTable, LootParameterSets.GENERIC);
    }

    @Override
    protected void validate(Map<ResourceLocation, LootTable> map, ValidationTracker validationtracker) {
        map.forEach((loc, table) -> LootTableManager.validateLootTable(validationtracker, loc, table));
    }
}
